Repository fga-eps-mds/2020.2-e-Vacina-Backend, pull requests merged in 2021-03, with the labels that each got.

#57 Arrumando o ambiente back-end
  .gitignore
  Dockerfile
  Makefile
  docker-compose.yml
  package-lock.json
  package.json
  src/index.js
Labels: Back-end, DevOps, Development

#65 docs(#48):updated the file arquitetura.md
  docs/assets/backend.png
  docs/assets/frontend.png
  docs/assets/pacotes_de_design.png
  docs/wiki/documento_arquitetura.md
  package-lock.json
  package.json
Labels: Sprint 3, documentation

#80 docs(#76):changes in the implantation vision of arquitetura.md
  docs/assets/backend.png
  docs/assets/frontend.png
  docs/wiki/documento_arquitetura.md
Labels: Sprint 4, documentation, enhancement

#93 Atualizando documento de arquitetura
  docs/assets/frontend.png
  docs/wiki/documento_arquitetura.md
Labels: Sprint 5, documentation

#106 Atualizando Documentos das Sprints
  docs/_navbar.md
  docs/_sidebar.md
  docs/assets/MapaConhecimentoSprint5.png
  docs/templates/planning_template.md
  docs/templates/review_template.md
  docs/wiki/Sprint0/result_sprint0.md
  docs/wiki/Sprint1/result_sprint1.md
  docs/wiki/Sprint2/documento_sprint2.md
  docs/wiki/Sprint2/result_sprint2.md
  docs/wiki/Sprint3/documento_sprint3.md
  docs/wiki/Sprint3/result_sprint3.md
  docs/wiki/Sprint4/documento_sprint4.md
  docs/wiki/Sprint4/result_sprint4.md
  docs/wiki/Sprint5/documento_sprint5.md
  docs/wiki/Sprint5/result_sprint5.md
  docs/wiki/Sprint6/documento_sprint6.md
  docs/wiki/Sprint6/result_sprint6.md
Labels: Back-end, Scrum Master, Sprint 4, Sprint 5, Sprint 6, documentation

#107 docs(#103): update prototipo.md
  docs/assets/Screen1.png
  docs/assets/Screen2.png
  docs/assets/Screen3.png
  docs/assets/Screen4.png
  docs/assets/Screen5.png
  docs/assets/initial-screens.jpg
  docs/assets/user-config.jpg
  docs/assets/vacinas-screens.jpg
  docs/prototipo.md
Labels: Sprint 6, documentation, enhancement

#110 Adicionando a apresentaço da Release 1 no README.md #109
  README.md
Labels: Release1, documentation
